### ISSUE TITLE
EventObserver

### ISSUE THREAD

**Issue by performanceArtist** [Hahahayabanan/FSD-4th-task#11]
Почему этот класс требует создания инстанса для каждого обрабатываемого события? Разве тебе нужен broadcast, когда на событие у тебя подписывается одна функция? Можешь это решение обосновать?

**Comment by Hahahayabanan** [comment]
Этот класс требует создания инстанса для каждого обрабатываемого события, чтобы не собирать данные и логику в кучу, потому что разные события отправляют разные данные,  обрабатываются разными функциями.
Сейчас на событие подписывается одна функция, но в будущем может понадобиться больше, поэтому broadcast нужен чтобы у observer была такая возможность.
