### ISSUE TITLE
setSettiings

### ISSUE THREAD

**Issue by performanceArtist** [Hahahayabanan/FSD-4th-task#15]
Зачем держать внутри столько фукнций? const setMin, const setMax и т.д. Они только метод раздувают и затрудняют читаемость - мало ли, что из окружения они могут использовать.

**Comment by performanceArtist** [comment]
![iffy](https://user-images.githubusercontent.com/43477987/71541317-ad1f7600-2989-11ea-8f33-1b6fc09a73ad.png)

Так не пойдёт - нужно подумать,  как избавиться от повторяющихся проверок. К тому же возвращаемый тип у isDefined неправильный.

**Comment by performanceArtist** [comment]
ISliderSettings[keyof ISliderSettings] - эта вещь у тебя не возвращает undefined или null, а ты её везде используешь там, где на это проверки ведутся.

**Comment by performanceArtist** [comment]
```  
setSettings(newSettings: ISliderSettings = {}) {
    const settings = newSettings;
```

Зачем создавать новую переменную?

**Comment by Hahahayabanan** [comment]
> ```
> setSettings(newSettings: ISliderSettings = {}) {
>     const settings = newSettings;
> ```
> 
> Зачем создавать новую переменную?

Чтобы не переопределять аргументы функции
![image](https://user-images.githubusercontent.com/43137324/71541544-13010300-2974-11ea-9bc5-6c59990d179e.png)

**Comment by performanceArtist** [comment]
Но ты же их по факту всё равно переопределяешь. Почему не const settings = {}?

**Comment by performanceArtist** [comment]
В общем лучше делать без переопределения переменных. В validateFrom/validateTo тоже не особенно нужен let.
