### ISSUE TITLE
MainView

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-4th-task#18]
Поскольку вью отрисовывается на основе модели, все настройки стоит хранить в модели, а во вью просто получать их: 

![Снимок экрана от 2020-01-13 23-22-00](https://user-images.githubusercontent.com/38564412/72289172-918bbf00-365b-11ea-8f0d-19c1bd76f22c.png)

**Comment by MorganaLF** [comment]
Цифры 0 и 1 в наименованиях ни о чем не говорят, стоит подбирать такие имена, которые раскроют сущность и назначение: пункт 1 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/variablesNaming.md

![Снимок экрана от 2020-01-13 23-23-22](https://user-images.githubusercontent.com/38564412/72289352-f810dd00-365b-11ea-9339-8ec85b8f219c.png)

Это ведь не просто указатели, они чем-то отличаются по своему назначению?

**Comment by MorganaLF** [comment]
Небольшое усовершенствование: чтобы не байндить каждый раз, можно использовать декораторы

![Снимок экрана от 2020-01-13 23-26-58](https://user-images.githubusercontent.com/38564412/72289490-4d4cee80-365c-11ea-8493-324fe07b8848.png)

**Comment by MorganaLF** [comment]
Зачем здесь HTML в именах? Если имеется ввиду, что это html-элемент, то, мне кажется, тут в имя будет лучше добавить слово element, по `this.pathHTML` не сразу понятно, что это такое 

![Снимок экрана от 2020-01-13 23-28-59](https://user-images.githubusercontent.com/38564412/72289739-c9473680-365c-11ea-9760-aa4d4981bb69.png)

**Comment by MorganaLF** [comment]
Учитывая то, что у тебя в MainView просто собираются вместе все элементы слайдера, мне кажется, будет логичнее вынести и вот эту часть кода в отдельный класс:

![Снимок экрана от 2020-01-13 23-33-34](https://user-images.githubusercontent.com/38564412/72289968-47a3d880-365d-11ea-9be2-c100c6699b68.png)

**Comment by MorganaLF** [comment]
А почему `Pointer` сам не диспатчит свое событие? По идее это его зона ответственности

![Снимок экрана от 2020-01-13 23-36-39](https://user-images.githubusercontent.com/38564412/72290232-c731a780-365d-11ea-9c99-3abe239cb768.png)

**Comment by Hahahayabanan** [comment]
> А почему `Pointer` сам не диспатчит свое событие? По идее это его зона ответственности
> 
> ![Снимок экрана от 2020-01-13 23-36-39](https://user-images.githubusercontent.com/38564412/72290232-c731a780-365d-11ea-9c99-3abe239cb768.png)

`Pointer` диспатчит своё событие в `mainView`, а `mainView` в `presenter`. Потому что `pointer` не знает о существовании других ему подобных, и не знает какой он, "первый" или "второй". А `mainView` определяет какой из них обновился и диспатчит это, вместе со значением.
![image](https://user-images.githubusercontent.com/43137324/72404395-9a20ea00-376e-11ea-9337-cfa140797426.png)
![image](https://user-images.githubusercontent.com/43137324/72404465-e5d39380-376e-11ea-95a4-c45c9f7071d6.png)

**Comment by MorganaLF** [comment]
> Pointer диспатчит своё событие, на него подписан mainView, а на mainView presenter. Потому что pointer не знает о существовании других ему подобных, и не знает какой он, "первый" или "второй". А mainView определяет какой из них обновился и диспатчит это, вместе со значением.

Ок, понятно. Да, это логично.

**Comment by MorganaLF** [comment]
Вот здесь странно получилось. Имя переменной `wasPointerMoved` подразумевает, что в ней лежит булево значение, а там лежит индекс. Было бы логичнее проверку на индекс (`=== -1`) вынести в эту переменную.

![Снимок экрана от 2020-01-16 09-36-00](https://user-images.githubusercontent.com/38564412/72499760-ca868800-3843-11ea-96f5-1bc83e857387.png)
