### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-4th-task#20]
Сейчас в package.json есть скрипт для автофикса, но нельзя просто пролинтить проект.

Если запустить линтер, есть немного ошибок и варнингов:

![Снимок экрана от 2020-01-14 11-10-27](https://user-images.githubusercontent.com/38564412/72325591-7f8f3800-36be-11ea-847b-fbe2ef9d1abe.png)

**Comment by Hahahayabanan** [comment]
В данном случае, не знаю имеет ли смысл вносить правки в правила линтера, потому что, данные ошибки, вероятно, не исправить
![image](https://user-images.githubusercontent.com/43137324/72403444-858f2280-376b-11ea-8047-a86847eeae7f.png)
![image](https://user-images.githubusercontent.com/43137324/72403474-9344a800-376b-11ea-9ffd-58090a75f7d2.png)

**Comment by MorganaLF** [comment]
Я думаю, здесь лучше не менять правила, а  задисейблить только для этих линий, поскольку проигнорировать эти правила нужно только в конкретных случаях.

**Comment by MorganaLF** [comment]
> Сейчас в package.json есть скрипт для автофикса, но нельзя просто пролинтить проект.

Надо добавить скрипт для просто линтинга, без автофикса. Каждый раз вручную запускать не удобно.

![Снимок экрана от 2020-01-16 09-13-52](https://user-images.githubusercontent.com/38564412/72498505-9493d480-3840-11ea-877e-a843f4785696.png)
