### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-4th-task#21]
А здесь точно нужен `PointerView`? Сейчас у тебя получается, что в тестах есть зависимости от другого класса. Лучше это замокать.

![Снимок экрана от 2020-01-16 10-12-29](https://user-images.githubusercontent.com/38564412/72501786-d45eba00-3848-11ea-9413-d4dc9a3a574b.png)

Все названия тестов выглядят одинаково, может, нужно больше конкретики? Хотелось бы по названию понимать, что конкретно тестируется

![Снимок экрана от 2020-01-16 10-13-56](https://user-images.githubusercontent.com/38564412/72501858-05d78580-3849-11ea-95b6-cf89ea98993b.png)

Опять же зависимости, юниты должны быть независимыми, чтобы протестить `PathView`, в теории тебе не нужно создавать `MainView`. Надо по всем тестам посмотреть этот момент

![Снимок экрана от 2020-01-16 10-16-43](https://user-images.githubusercontent.com/38564412/72502199-ccebe080-3849-11ea-833a-e5c47cfc6895.png)

**Comment by MorganaLF** [comment]
Еще сразу не заметила, что у тебя нет скрипта для coverage, хотелось бы посмотреть процент покрытия тестами.

**Comment by Hahahayabanan** [comment]
> Еще сразу не заметила, что у тебя нет скрипта для coverage, хотелось бы посмотреть процент покрытия тестами.

Coverage report генерируется в папке tests-coverage
![image](https://user-images.githubusercontent.com/43137324/72630178-3d3e5300-396b-11ea-89c1-2badb5cc0d46.png)

**Comment by MorganaLF** [comment]
Я имею ввиду, что нет скрипта в package.json, чтобы запустить coverage из консоли, и  в консоли же глянуть.

**Comment by MorganaLF** [comment]
В папке tests-coverage у меня, кстати, сейчас ничего не генерируется из-за ошибки сборки (первое ишью)

**Comment by Hahahayabanan** [comment]
Сори, я пока не знаю как такой скрипт должен выглядеть, это он?

![image](https://user-images.githubusercontent.com/43137324/72659438-1f0f3c00-39d9-11ea-84fb-c0f3a7d68dc4.png)

**Comment by MorganaLF** [comment]
Да, это оно. Но я сейчас у тебя даже `test` не могу запустить. Короче, надо первое ишью сначала закрыть, потому что из-за этой ошибки все ломается)

**Comment by Hahahayabanan** [comment]
> Да, это оно. Но я сейчас у тебя даже `test` не могу запустить. Короче, надо первое ишью сначала закрыть, потому что из-за этой ошибки все ломается)

Я же вроде пофиксил её? У меня на линукс её больше нет

**Comment by MorganaLF** [comment]
> Я же вроде пофиксил её? У меня на линукс её больше нет

Точно, сейчас все ок
