### ISSUE TITLE
PathView

### ISSUE THREAD

**Issue by Hahahayabanan** [Hahahayabanan/FSD-4th-task#22]
Класс хранит копии инстансов `PointerView`, которые нужно обновлять вручную, что было неудачной идеей. Поскольку из класса нет возможности запрашивать откуда-либо данные о положении поинтеров, было решено эти данные сохранять и обновлять срабатыванием уже существующих событий.

**Comment by MorganaLF** [comment]
А почему тут состояние достается из имени класса? Нельзя `isVertical`, например, параметром прокидывать из главной вьюхи?

![Снимок экрана от 2020-01-17 07-41-30](https://user-images.githubusercontent.com/38564412/72584890-e4d06c80-38fc-11ea-89b8-dbeb7c67e11c.png)

**Comment by MorganaLF** [comment]
Не совсем поняла, в чем именно проблема была?

> Класс хранит копии инстансов PointerView, которые нужно обновлять вручную, что было неудачной идеей. 

То, что у тебя хранились инстансы классов, которые использует `PathView`, вполне нормально

> Поскольку из класса нет возможности запрашивать откуда-либо данные о положении поинтеров

А нельзя, например, чтобы каждый поинтер диспатчил свое событие с координатами, а `PathView` слушал эти события и диспатчил дальше наверх?

По-моему, сейчас как-то странно получилось: `PathView` диспатчит события, связанные с поинтерами, но ничего о поинтерах не знает. 
Мне кажется, нужно или полностью отделять тогда поинтеры и делать все, что с ними связано, из главной вьюхи, или хранить их в `PathView` и слушать их события там же.

**Comment by Hahahayabanan** [comment]
> Не совсем поняла, в чем именно проблема была?
> 
> > Класс хранит копии инстансов PointerView, которые нужно обновлять вручную, что было неудачной идеей.
> 
> То, что у тебя хранились инстансы классов, которые использует `PathView`, вполне нормально. Точно так же, как у тебя в главной вьюхе хранится `Path`.
> 
У меня хранились инстансы `PointerView` и в `MainView` и в `PathView`.
> > Поскольку из класса нет возможности запрашивать откуда-либо данные о положении поинтеров
> 
> А нельзя, например, чтобы каждый поинтер диспатчил свое событие с координатами, а `PathView` слушал эти события и диспатчил дальше наверх?
Дело в том, что `PointerView` диспатчит события перетаскивания поинтера, а `PathView` диспатчит событие клика на линию слайдера, и на основе текущего положения поинтеров, определяет какой из них должен переместиться. + Ему нужно знать положение поинтеров для того, чтобы иметь рамки "красной" для линии, соединяющей их
> 
> По-моему, сейчас как-то странно получилось: `PathView` диспатчит события, связанные с поинтерами, но ничего о поинтерах не знает.
> Мне кажется, нужно или полностью **отделять тогда поинтеры и делать все, что с ними связано, из главной вьюхи**, или хранить их в `PathView` и слушать их события там же.
Примерно так было до #18, где я вынес это в отдельный класс

Перенесу тогда инициализацию и инстансы `PointerView` из `MainView` в `PathView`

**Comment by Hahahayabanan** [comment]
> А почему тут состояние достается из имени класса? Нельзя `isVertical`, например, параметром прокидывать из главной вьюхи?
> 
> ![Снимок экрана от 2020-01-17 07-41-30](https://user-images.githubusercontent.com/38564412/72584890-e4d06c80-38fc-11ea-89b8-dbeb7c67e11c.png)

Я их убрал, и ничего другого не придумал
> Поскольку вью отрисовывается на основе модели, все настройки стоит хранить в модели, а во вью просто получать их:
> 
> ![Снимок экрана от 2020-01-13 23-22-00](https://user-images.githubusercontent.com/38564412/72289172-918bbf00-365b-11ea-8f0d-19c1bd76f22c.png)

**Comment by MorganaLF** [comment]
> Перенесу тогда инициализацию и инстансы PointerView из MainView в PathView

Да, думаю, так лучше всего должно получиться

**Comment by MorganaLF** [comment]
> Я их убрал в #18 , и ничего другого взамен не придумал

Поскольку вью имеет зависимость от модели, вью вполне может знать о модели и получать ее параметром в конструктор.

А дальше уже можно внутри главной вьюхи обращаться к this.model.getSettings() и получать / передавать вниз необходимые значения

**Comment by Hahahayabanan** [comment]
> > Я их убрал в #18 , и ничего другого взамен не придумал
> 
> Поскольку вью имеет зависимость от модели, вью вполне может знать о модели и при создании получать ее параметром в свой конструктор.
> 
> А дальше уже можно внутри главной вьюхи обращаться к `this.model.getSettings()` и получать / передавать вниз необходимые значения

Но это ведь противоречит MVP паттерну?
_The presenter acts as a mediator which talks to both the view and model, however both of these are isolated from each other._
![image](https://user-images.githubusercontent.com/43137324/72613021-eb380600-3947-11ea-954b-773555ccd7c9.png)

**Comment by MorganaLF** [comment]
> Но это ведь противоречит MVP паттерну?

Да, думаю, ты прав, это получится active view, а нужно, чтобы было passive view. 
В таком случае нужно это разруливать в презентере. Например, прокидывать опции из презентера в главную вью, дальше из главной вью в метод toggleOrientation, и удалять-навешивать события заново с нужными опциями.

**Comment by MorganaLF** [comment]
Можно закрывать это ишью
