### ISSUE TITLE
Метод setSettings в модели

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-4th-task#24]
Сейчас в этом методе все несколько запутанно. 
Сначала ты валидируешь все вот здесь

```
Object.keys(newSettings).forEach((key) => {
      settings[key] = this.validateSettingType(key, newSettings[key]);
    });
```

Потом ниже опять делаешь какие-то проверки с теми же опциями. 
У тебя в целом в модели всё хорошо написано сейчас, этот метод единственный хотелось бы как-то рефакторнуть. Еще непонятно, зачем тут сейчас используется рекурсия

![Снимок экрана от 2020-01-20 15-38-08](https://user-images.githubusercontent.com/38564412/72727031-f5057780-3b9a-11ea-9ab9-f1ba66ee5664.png)

Мне кажется, тут  чтобы не проверять на `isDefined`, можно например сразу прямо в 
`forEach` присваивать опции как-нибудь так: `this[key] = newValue`; Возможно, вместо `Object.keys` тут будет удобнее `Object.entries`.

**Comment by Hahahayabanan** [comment]
> Мне кажется, тут чтобы не проверять на `isDefined`, можно например сразу прямо в
> `forEach` присваивать опции как-нибудь так: `this[key] = newValue`; 

Проверку `isDefined` я сделал, чтобы приходящие свойства применялись последовательно в том порядке, который я установил. Я не могу знать, какие параметры придут, и в какой последовательности. 
![image](https://user-images.githubusercontent.com/43137324/72741484-2abd5700-3bc1-11ea-9f7b-7c3961bedc1a.png)

А так я уверен какие параметры уже были установлены и мне не нужно делать выбор с каким сравнивать: с пришедшим, если он есть, или с находящимся в модели. Такая проверка сейчас в одном месте, а пришлось бы делать везде.
![image](https://user-images.githubusercontent.com/43137324/72741846-ea120d80-3bc1-11ea-9699-2e4886a2dcde.png)

> Еще непонятно, зачем тут сейчас используется рекурсия

Рекурсия здесь используется не для рекурсии, а для обновления других свойств, после применения данных, потому что, они, очень вероятно, будут изменены.
Т.е. этот код
```
if (this.isDefined(min)) {
      this.settings.min = this.validateMin(newSettings);
      this.setSettings({ from: this.settings.from, to: this.settings.to });
}
```
Можно заменить этим
```
if (this.isDefined(min)) {
      this.settings.min = this.validateMin(newSettings);
      this.validateFrom({ from: this.settings.from });
      this.validateTo({ to: this.settings.to });
}
```
Мне показался первый вариант немного нагляднее

**Comment by MorganaLF** [comment]
Хм. Ну пусть тогда пока так остается. Но если появятся идеи, как это рефакторнуть, не усложняя остальную реализацию модели, будет хорошо.
