### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-4th-task#25]
При установлении отрицательного значения появляется какой-то баг, бегунок застревает и не двигается, и в подсказке отображает какое-то некорректное значение

![Снимок экрана от 2020-01-21 19-11-54](https://user-images.githubusercontent.com/38564412/72821929-489ec080-3c82-11ea-83e0-75535f3d756b.png)

**Comment by Hahahayabanan** [comment]
Пофиксил. Это я не добавил `validateNumber` в метод `validateMin`, когда разбирал `setSettings`

**Comment by MorganaLF** [comment]
Еще иногда что-то случается с положением поинтера, один отцентрирован, а второй нет

![Снимок экрана от 2020-01-22 09-39-33](https://user-images.githubusercontent.com/38564412/72871205-43318c80-3cfb-11ea-85b9-5ae75b0179d5.png)
