### ISSUE TITLE
Типы аргументов у слайдера

### ISSUE THREAD

**Issue by performanceArtist** [Hahahayabanan/FSD-4th-task#5]
`...args: any` - получается, туда что угодно по типами можно передать? Так со стороны не понятно даже приблизительно, как плагин вызывать. Надо более конкретно сделать.

**Comment by performanceArtist** [comment]
В `getStart` не нужно дублировать типы, которые ты указал в интерфейсе. Также сейчас там есть проблема в том плане, что в качестве значения ключа можно передать любую строку. Посмотри в сторону keyof.

**Comment by Hahahayabanan** [comment]
Немного изменил эту часть кода, как сделать это всё используя keyof я не понимаю

**Comment by performanceArtist** [comment]
Если у тебя один плагин, навешивать множество функций на fn не нужно. Для плагина должен быть единый интерфейс. keyof использовать можно для работы с ключами твоего интерфейса ISliderOptions - в чём проблема?
